### ISSUE TITLE
Struct unpacking fails for early 2.7 versions

### ISSUE THREAD

**Issue by larsyencken** [valohai/ulid2#2]
On Python 2.7.1, the method `get_ulid_time()` and perhaps others fails with an exception.

This is because `struct.unpack(spec, bytes)` only begins accepting unicode specs in some later minor release of Python 2.7, and the file header has `from __future__ import unicode_literals`.

The fix is easy, I'll put together a patch for it.

**Comment by larsyencken** [comment]
Here's the stacktrace:

```
Python 2.7.6 (default, Mar  8 2017, 14:22:45)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ulid2
>>> u = ulid2.generate_ulid_as_base32()
>>> u
u'01BAQ8K6FNHV6QWBKRYNJZ15CS'
>>> ulid2.get_ulid_time(u)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../env/lib/python2.7/site-packages/ulid2.py", line 141, in get_ulid_time
    timestamp = struct.unpack('!Q', ts_bytes)[0]
TypeError: Struct() argument 1 must be string, not unicode
```

**Comment by akx** [comment]
Thanks for the catch!

I figure just turning that to `b'!Q'` instead of `'!Q'` will do the trick and should be compatible with Python 3 too.

**Comment by larsyencken** [comment]
Yeah, exactly. Thanks for the fast merge, and for creating the module in the first place 👍

**Comment by akx** [comment]
Thank you!
Released in https://pypi.org/project/ulid2/0.1.1/ :)
