### ISSUE TITLE
Text ULID parsing squashes high bits

### ISSUE THREAD

**Issue by larsyencken** [valohai/ulid2#4]
We discovered this problem by accident, when we realised that some (very far future ULIDs) the ULIDs appear to be not time-ordering.

For example, ULIDs that start with 0, 8, G or R are mapped to the same place:

```pycon
>>> import ulid2
>>> ulid2.ulid_to_binary('0' + '0' * 25)
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>>> ulid2.ulid_to_binary('8' + '0' * 25)
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>>> ulid2.ulid_to_binary('G' + '0' * 25)
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>>> ulid2.ulid_to_binary('R' + '0' * 25)
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

It looks like the parsing of the first character has a cycle in it, instead of generating a new sequence of binary ULIDs.

**Comment by akx** [comment]
Hmm. Good catch! The same problem appears in `oklog/ulid`, so I raised the equivalent issue there.
