### ISSUE TITLE
Add monotonic entropy for ULIDs created in the same millisecond?

### ISSUE THREAD

**Issue by itdaniher** [valohai/ulid2#7]
The latest version of the ULID spec suggests / recommends / requires the entropy to be incremented (by one) for each subsequent ULID creation in the same millisecond. This keeps ordering easy, but isn't necessarily ideal for some applications. The @oklog [implementation](https://godoc.org/github.com/oklog/ulid#Monotonic) of ULID functionality in Go increments by a random number for subsequent calls.

Bit of discussion at https://github.com/ahawker/ulid/issues/306.

**Comment by akx** [comment]
Closed via #8. Thanks!
